CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Interleukin-6      MNFTEGCEATGRRPGSAGSRRRRAPRPGPVALLPLLLPLLLPPAAAVPLPAAADSSGEVG
isoform            MNFTEGCEATGRRP---GSRHRRAPRPGPAALLLLLLPLLPPPAAAAPLP---DSSGEAG
[Centrocercus      MNFTEGCEATGRRPGSAGSRRRKAPRPGPAALLLLLLPLLLPPAAAAPLPAAADSSGEAG
[Tympanuchus       MNFTEGCEATGRRPGSAGSRRRRAPRPGPAALLLLLLPLLLPPAAAAPLPAAADSSGEAG
[Lagopus           MNFTEGCEATGRQPGSAGSSRRRAPRPGPAALLLLLLSLLLPPAAAAPLPAAADSSGEAG
                   ************.*   ** .*.******.*** ***.** *****.***   *****.*

Interleukin-6      LEEEAGARRALLDCEPLARVLRDRAVQLQDEMCKKFTVCENSMEMLVRNNLNLPKVTEED
isoform            LEEEAG---ALPDCESLAWLLHNRAARLQDEMCEKFTVCENSMEMLVQNNLNLPKVTEED
[Centrocercus      LEEEAGARRALPDCESLAWLLHSRAARLQDEMCEKFSVCENSMEMLVRNNLNLPKVTEED
[Tympanuchus       LEEEAGARRALPDCESLAWLLHSRAARLQDEMCEKFSVCENSMEMLVRNNLNLPKVTEED
[Lagopus           LEEEAGARRALPDCESLAWLLHSRAARLQDEMCEKFSVCENSMEMLVRNNLNLPKVTEED
                   ******   ** ***.**.:*..**..******:**:**********.************

Interleukin-6      GCLLAGFDEEKCLTKLFSGLFAFQTYLEFIQETFDSEKQNVESLCYSTKHLAATIRQMVI
isoform            GCLLAGFDEEKCLRKLSSGLFAFQTYLEFIQETFASEKQNVESLCYGTKHLATT-RQMVI
[Centrocercus      GCLLAGFDEEKCLRKLSSGLFAFQTYLEFIQETFASEKQNVESLCYGTKHLAATIRQMVI
[Tympanuchus       GCLLAGFDEEKCLRKLSSGLFAFQTYLEFIQETFASEKQNVESLCYGTKHLAATIRQMVI
[Lagopus           GCLLAGFDEEKCLRKLSSGLFAFQTYLQFIQETFASEKQNVESLCYGTKHLAATIRQMVI
                   ************* ** **********:****** ***********.*****:* *****

Interleukin-6      NPDEVVIPDSAAQKSLLANLKSDKDWIEKITMHLILRDFTSFMEKTVRAVRYLKKTRSFS
isoform            NPDEVVIPDSASQKSLLSKLKSDKAWIEKITTHLILRDFTSFMEKTVRAVRYLKNTRSFS
[Centrocercus      NPDEVIIPDSATQKSLLAKLKSDKAWIEKITTHLILRDFTSFMENTVRAVRYLKNTRSFS
[Tympanuchus       NPDEVIIPDSATQKSLLAKLKSDKAWIEKITTHLILRDFTSFMENTVRAVRYLKNTRSFS
[Lagopus           NPDKVIIPDSATQKSLLAKLKSDKAWIEKITTHLILRDFTSFMEKTVRAVRYLKNTRSFS
                   ***:*:*****:*****::***** ****** ************:*********:*****

Interleukin-6      A
isoform            A
[Centrocercus      A
[Tympanuchus       A
[Lagopus           A
                   *
